import type { Issue } from "../types";

interface SeedIssueOptions {
  projectId: string;
  sprintId: string;
  backlogSprintId: string;
  nowIso: string;
  yesterdayIso: string;
}

export const getSeedIssues = ({
  projectId,
  sprintId,
  backlogSprintId,
  nowIso,
  yesterdayIso,
}: SeedIssueOptions): Issue[] => [
  {
    id: "i-1",
    key: "DEMO-1",
    projectId,
    title: "ログイン画面の実装",
    type: "Story",
    status: "Done",
    priority: "High",
    assigneeId: "u1",
    reporterId: "u2",
    sprintId,
    labels: ["frontend"],
    createdAt: yesterdayIso,
    updatedAt: nowIso,
    storyPoints: 5,
    watcherIds: ["u1"],
    comments: [],
    workLogs: [],
    history: [],
    links: [],
    attachments: [],
  },
  {
    id: "i-2",
    key: "DEMO-2",
    projectId,
    title: "APIのCORSエラー修正",
    type: "Bug",
    status: "In Progress",
    priority: "Highest",
    assigneeId: "u1",
    reporterId: "u1",
    sprintId,
    labels: ["backend", "bug"],
    createdAt: nowIso,
    updatedAt: nowIso,
    storyPoints: 3,
    watcherIds: ["u1", "u2"],
    comments: [],
    workLogs: [],
    history: [],
    links: [],
    attachments: [],
  },
  {
    id: "i-3",
    key: "DEMO-3",
    projectId,
    title: "ダッシュボードのデザイン",
    type: "Task",
    status: "To Do",
    priority: "Medium",
    assigneeId: "u3",
    reporterId: "u1",
    sprintId,
    labels: ["design"],
    createdAt: nowIso,
    updatedAt: nowIso,
    storyPoints: 2,
    watcherIds: [],
    comments: [],
    workLogs: [],
    history: [],
    links: [],
    attachments: [],
  },
  {
    id: "i-4",
    key: "DEMO-4",
    projectId,
    title: "ユーザー通知機能",
    type: "Story",
    status: "To Do",
    priority: "High",
    assigneeId: "u1",
    reporterId: "u2",
    sprintId,
    labels: ["feature"],
    createdAt: nowIso,
    updatedAt: nowIso,
    storyPoints: 8,
    watcherIds: [],
    comments: [],
    workLogs: [],
    history: [],
    links: [],
    attachments: [],
  },
  {
    id: "i-5",
    key: "DEMO-5",
    projectId,
    title: "リリースマニュアルの作成",
    type: "Task",
    status: "To Do",
    priority: "Low",
    assigneeId: undefined,
    reporterId: "u1",
    sprintId: backlogSprintId,
    labels: ["docs"],
    createdAt: nowIso,
    updatedAt: nowIso,
    storyPoints: 1,
    watcherIds: [],
    comments: [],
    workLogs: [],
    history: [],
    links: [],
    attachments: [],
  },
];
